### ISSUE TITLE
always display primary avatar for a user in admin

### ISSUE THREAD

**Issue by allenling** [jezdez/django-avatar#76]
eg:
user A has 3 avatars, a.jpg,b.jpg,c.jpg, and the primary avatar is a.jpg.
 at admin page, right avatar url but wrong display. always display a.jpg

![wrong display](https://f.cloud.github.com/assets/2723570/1893921/4fa8b8dc-7ac2-11e3-9c89-b99911f5a81a.jpg)

![right display](https://f.cloud.github.com/assets/2723570/1893924/bfc77d10-7ac2-11e3-9d06-84036e341337.jpg)

**Comment by grantmcconnaughey** [comment]
Closed in #94
